default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'mofu_blog_app' } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  host:     <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port:     <%= ENV.fetch('DATABASE_PORT') { 5432 } %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'mofu_blog_app_test' } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  host:     <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port:     <%= ENV.fetch('DATABASE_PORT') { 5432 } %>

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { nil } %>
  pool: 16

staging:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { nil } %>
  pool: 16
